<?php

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

class bt_bb_raw_content extends BT_BB_Element {

	function handle_shortcode( $atts, $content ) {
		extract( shortcode_atts( apply_filters( 'bt_bb_extract_atts_' . $this->shortcode, array(
			'raw_content' => ''
		) ), $atts, $this->shortcode ) );
		
		$class = array( $this->shortcode );

		do_action( $this->shortcode . '_before_extra_responsive_param' );
		foreach ( $this->extra_responsive_data_override_param as $p ) {
			if ( ! is_array( $atts ) || ! array_key_exists( $p, $atts ) ) continue;
			$this->responsive_data_override_class(
				$class, $data_override_class,
				apply_filters( $this->shortcode . '_responsive_data_override', array(
					'prefix' => $this->prefix,
					'param' => $p,
					'value' => $atts[ $p ],
				) )
			);
		}

		$raw = base64_decode( $raw_content );

		// This element exists to emit unfiltered HTML/JS, so it is only safe when the
		// person who stored it was trusted to publish unfiltered HTML. The save-time
		// gate in bt_bb_save_pre() cannot be the only control -- it inspects content
		// on its way into the database, where save-filter ordering can leave it
		// looking at a different string than the one actually stored. Deciding here,
		// against the stored post's author, is evaluated on exactly what will be
		// printed and stays meaningful for anonymous visitors.
		if ( ! function_exists( 'bt_bb_author_can_unfiltered_html' ) || ! bt_bb_author_can_unfiltered_html() ) {
			$raw = wp_kses_post( $raw );
		}

		$output = '<div class="' . esc_attr( implode( ' ', $class ) ) . '">' . $raw . '</div>';
		
		$output = apply_filters( 'bt_bb_general_output', $output, $atts );
		$output = apply_filters( $this->shortcode . '_output', $output, $atts );
		
		return $output;
		
	}
	
	function add_params() {
		// removes default params from BT_BB_Element
	}

	function map_shortcode() {
		bt_bb_map( $this->shortcode, array( 'name' => esc_html__( 'Raw Content', 'bold-page-builder' ), 'description' => esc_html__( 'Raw HTML/JS content', 'bold-page-builder' ), 'icon' => $this->prefix_backend . 'icon' . '_' . $this->shortcode,
			'params' => array(
				array( 'param_name' => 'raw_content', 'type' => 'textarea_object', 'heading' => esc_html__( 'Raw content', 'bold-page-builder' ), 'description' => esc_html__( 'Do NOT use HTML content generated by Bold Builder.', 'bold-page-builder' ) )
			)
		) );
	}
}